---
server:
  port: 8086
  servlet:
    context-path: /scaffold

---
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scaffold?&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: test
    async-init: true
    initial-size: 5                             # 初始化建立的连接数
    max-active: 100                             # 最大连接池数量
    max-wait: 60000                             # 获取连接的最大等待时间，单位毫秒
    validation-query: select 'x'               # 检测连接是否有效
    validation-query-timeout: 1               # 检测连接是否超时，单位秒
    test-on-borrow: false                      # 申请连接时，是否执行validationQuery检测
    test-on-return: false                      # 归还连接时，是否执行validationQuery检测
    test-while-idle: true                      # 如果空闲时间大于配置时间，是否执行validationQuery检测
    min-evictable-idle-time-millis: 600000    # 连接保持空闲而不被驱逐的最小时间
    use-unfair-lock: true
    default-transaction-isolation: 2          # 事务的默认隔离级别

---
# Redis 配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: scaffold
    pool:
      max-active: 80      # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 3000      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 20        # 连接池中的最大空闲连接数
      min-idle: 5         # 连接池中的最小空闲连接数
      timeout: 3000       # 连接超时时间（毫秒），默认2000

---
# Dubbo 服务提供配置
spring:
  application:
    name: spring-cloud-scaffold-provider
  dubbo:
#    application:
#      logger: slf4j
    server: true
    registry: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan:
      base-packages: com.soojoe.scaffold.api.share
    provider:
      timeout: 10000
      retries: 0
      delay: -1
---
# rabbitmq相关配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: scaffold
    password: scaffold
    publisherConfirms: true
    virtualHost: /